trigger:
- main

pool:
  vmImage: windows-latest

steps:
- task: Maven@4
  inputs:
    mavenPomFile: "pom.xml"
    mavenOptions: "-Xmx3072m"
    javaHomeOption: "JDKVersion"
    jdkVersionOption: "1.11"
    jdkArchitectureOption: "x64"
    publishJUnitResults: true
    testResultsFiles: "**/TEST-*.xml"
    goals: "package"
- task: Bash@3
  inputs:
      targetType: 'inline'
      script: |
        # Write your commands here
        
        echo 'Hello world from the task assistant'
